# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0004_auto_20170228_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='join',
            field=models.ManyToManyField(related_name='joiner', to='black_belt.User'),
        ),
    ]
