# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0005_trip_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='travelfrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='travelto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
