# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0006_auto_20170228_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertrip', to='black_belt.User'),
        ),
    ]
