# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0007_trip_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='join',
        ),
        migrations.AddField(
            model_name='trip',
            name='joiner',
            field=models.ManyToManyField(related_name='join', to='black_belt.User'),
        ),
    ]
